server:
  servlet:
    session:
      tracking-modes: cookie # URL에 JSESSIONID가 붙어서 나가는 설정을 해제

spring:
  web:
    resources:
      # ResourceHttpRequestHandler를 매핑하지 않음. 인터셉터 적용 시 404에러를 출력하기 위해서 false로 설정하였음.
      # 이 옵션을 사용 시 static에 있는 resource를 찾지 못함.
      # resource를 사용하는 경우, WebMvcConfigurer의 addResourceHandlers에 등록할 것.
      add-mappings: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true # sql을 로깅
        format_sql: true # sql을 보기 좋게 정렬
        highlight_sql: true # sql에 색깔을 추가

logging:
  level:
    org.hibernate:
      sql: debug # 이 옵션을 사용하면 System.out 방식이 아니라 Logger를 사용하여 로깅
#      type.descriptor.sql: trace # sql에 ?로 표시되는 내용 출력
